Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : solicitar dois valores e exibir o resultado
// Autor(a)    : Amanda Vitoria
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis 
    gavetaA:inteiro
    gavetaB:inteiro
    soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreval("Amanda")
     Escreval("Possui 19 anos")

Fimalgoritmo